# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbdoc\measurement.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 740)
        Form.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(500, 270, 350, 200))
        self.lcdNumber.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(206, 206, 206);")
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setProperty("intValue", 10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(150, 620, 971, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
