# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbdoc\ardnotfound.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ardnotfound(object):
    def setupUi(self, ardnotfound):
        ardnotfound.setObjectName("ardnotfound")
        ardnotfound.resize(1280, 800)
        ardnotfound.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.label = QtWidgets.QLabel(ardnotfound)
        self.label.setGeometry(QtCore.QRect(100, 150, 1100, 450))
        self.label.setStyleSheet("color: rgb(255,255,255)")
        self.label.setObjectName("label")

        self.retranslateUi(ardnotfound)
        QtCore.QMetaObject.connectSlotsByName(ardnotfound)

    def retranslateUi(self, ardnotfound):
        _translate = QtCore.QCoreApplication.translate
        ardnotfound.setWindowTitle(_translate("ardnotfound", "Form"))
        self.label.setText(_translate("ardnotfound", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:700;\">Arduino not found! </span></p><p><span style=\" font-size:48pt;\">Please check connections and reboot!</span></p></body></html>"))
