# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbdoc\datarepr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 740)
        font = QtGui.QFont()
        font.setPointSize(20)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(50, 40, 1180, 520))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_lk = QtWidgets.QPushButton(Form)
        self.pushButton_lk.setGeometry(QtCore.QRect(50, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_lk.setFont(font)
        self.pushButton_lk.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_lk.setObjectName("pushButton_lk")
        self.pushButton_lr = QtWidgets.QPushButton(Form)
        self.pushButton_lr.setGeometry(QtCore.QRect(200, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_lr.setFont(font)
        self.pushButton_lr.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_lr.setObjectName("pushButton_lr")
        self.pushButton_lm = QtWidgets.QPushButton(Form)
        self.pushButton_lm.setGeometry(QtCore.QRect(350, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_lm.setFont(font)
        self.pushButton_lm.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_lm.setObjectName("pushButton_lm")
        self.pushButton_lz = QtWidgets.QPushButton(Form)
        self.pushButton_lz.setGeometry(QtCore.QRect(500, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_lz.setFont(font)
        self.pushButton_lz.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_lz.setObjectName("pushButton_lz")
        self.pushButton_rz = QtWidgets.QPushButton(Form)
        self.pushButton_rz.setGeometry(QtCore.QRect(650, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_rz.setFont(font)
        self.pushButton_rz.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_rz.setObjectName("pushButton_rz")
        self.pushButton_rm = QtWidgets.QPushButton(Form)
        self.pushButton_rm.setGeometry(QtCore.QRect(800, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_rm.setFont(font)
        self.pushButton_rm.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_rm.setObjectName("pushButton_rm")
        self.pushButton_rr = QtWidgets.QPushButton(Form)
        self.pushButton_rr.setGeometry(QtCore.QRect(950, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_rr.setFont(font)
        self.pushButton_rr.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_rr.setObjectName("pushButton_rr")
        self.pushButton_rk = QtWidgets.QPushButton(Form)
        self.pushButton_rk.setGeometry(QtCore.QRect(1100, 630, 130, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_rk.setFont(font)
        self.pushButton_rk.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0)\n"
"")
        self.pushButton_rk.setObjectName("pushButton_rk")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(500, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(640, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(790, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(950, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(1100, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(900, 0, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 127);\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_lk.setText(_translate("Form", "PushButton"))
        self.pushButton_lr.setText(_translate("Form", "PushButton"))
        self.pushButton_lm.setText(_translate("Form", "PushButton"))
        self.pushButton_lz.setText(_translate("Form", "PushButton"))
        self.pushButton_rz.setText(_translate("Form", "PushButton"))
        self.pushButton_rm.setText(_translate("Form", "PushButton"))
        self.pushButton_rr.setText(_translate("Form", "PushButton"))
        self.pushButton_rk.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">left <br/>pinky</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">left <br/>ringfinger</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">left <br/>middlefinger</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">left <br/>index</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">right<br/>index</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">right <br/>middlefinger</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">right <br/>ringfinder</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">right <br/>pinky</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Continue"))
