# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbdoc\initials.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_initials(object):
    def setupUi(self, initials):
        initials.setObjectName("initials")
        initials.resize(1280, 740)
        initials.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.label = QtWidgets.QLabel(initials)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(420, 190, 471, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,255,255)")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(initials)
        self.textEdit.setGeometry(QtCore.QRect(410, 290, 461, 70))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(initials)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(170, 420, 921, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(initials)
        self.pushButton.setGeometry(QtCore.QRect(880, 290, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(initials)
        QtCore.QMetaObject.connectSlotsByName(initials)

    def retranslateUi(self, initials):
        _translate = QtCore.QCoreApplication.translate
        initials.setWindowTitle(_translate("initials", "Form"))
        self.label.setText(_translate("initials", "Please enter your initials:"))
        self.textEdit.setHtml(_translate("initials", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:32pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("initials", "Initials already taken! Please add another identifier! \n"
"(For example a number)"))
        self.pushButton.setText(_translate("initials", "Check"))
